Move node-fetch to dependencies
`node-fetch` should be in the `dependencies`. If not, the module will return:

```sh
  ● Test suite failed to run

    Cannot find module 'node-fetch' from 'server.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (node_modules/fetch-mock/src/server.js:2:15)
```

Workaround is to include it in the parent project, which is not optimal imho.